# Generated by Django 5.1.6 on 2025-02-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='insight',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='category',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AssociatedCompany',
        ),
        migrations.DeleteModel(
            name='CompanyCategory',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='InsightsCategory',
        ),
        migrations.DeleteModel(
            name='Insights',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
