# Generated by Django 5.1.5 on 2025-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
