# Generated by Django 5.1.6 on 2025-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.ImageField(blank=True, null=True, upload_to='client/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='talent.language'),
        ),
    ]
