# Generated by Django 5.1.6 on 2025-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_language_client_client_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(to='talent.language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(to='talent.skill'),
        ),
    ]
