# Generated by Django 5.1.6 on 2025-03-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_profile_language_alter_profile_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='talent.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='available_to',
            field=models.ManyToManyField(to='talent.availableto'),
        ),
    ]
