# Generated by Django 5.1.6 on 2025-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_availableto_project_tag_profile_available_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='talent.skill'),
        ),
    ]
