# Generated by Django 5.1.7 on 2025-04-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_insights_featured_image'),
        ('talent', '0010_alter_education_school_alter_education_start_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insight.associatedcompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.ManyToManyField(related_name='model', through='talent.Client', to='insight.associatedcompany'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='talent.profile'),
        ),
    ]
