# Generated by Django 5.1.4 on 2025-04-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_insights_featured_image'),
        ('talent', '0011_remove_client_client_remove_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='model', through='talent.Client', to='insight.associatedcompany'),
        ),
    ]
