# Generated by Django 5.1.4 on 2025-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0012_alter_profile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
