# Generated by Django 5.1.4 on 2025-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0013_profile_linkedin_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
