# Generated by Django 5.1.4 on 2025-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_alter_profile_linkedin_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_data',
            field=models.BooleanField(default=False),
        ),
    ]
