# Generated by Django 5.1.4 on 2025-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_alter_profile_linkedin_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project/AI.jpg', null=True, upload_to='project/'),
        ),
    ]
