[tool.poetry]
name = "quid-ai"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
django = "5.1.4"
djangorestframework = "3.15.2"
pillow = "*"
django-filter = "24.3" 
python-dotenv = "1.0.1"
psycopg2-binary = "2.9.10"
drf-nested-routers = "0.94.1"
drf-yasg = "1.21.8"
django-allauth = "65.5.0"
requests = "2.32.3"
drf-social-oauth2 = "3.1.0"
django-cors-headers = "4.6.0"
celery = "5.3.4"
redis = "^5.2.1"
django-ckeditor-5 = "0.2.17"
