version: '3.8'

services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    image: backend-qa-image:latest
    container_name: backend-qa
    command: sh -c "ls && poetry install --no-root && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ../Backend/core/.env
    networks:
      - quid-ai-nw
