version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-qa
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      quid-ai-nw:
    volumes:
      - ../frontend:/app
    command: sh -c "ls && npm run dev"

