version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-qa
    ports:
      - "8007:3000"
    env_file:
      - .env 
    networks:
      quid-ai-nw:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
