# Generated by Django 5.1.6 on 2025-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='insight',
        ),
    ]
