# Generated by Django 5.1.6 on 2025-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/'),
        ),
    ]
