# Generated by Django 5.1.4 on 2025-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_insights_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
