# Generated by Django 5.1.4 on 2025-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_alter_faq_created_by_alter_testimonial_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associatedcompany',
            name='category',
        ),
        migrations.AddField(
            model_name='associatedcompany',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='company_category', to='insight.companycategory'),
        ),
    ]
