# Generated by Django 5.1.4 on 2026-05-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_alter_faq_created_by_alter_testimonial_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='associatedcompany',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_company_per_category'),
        ),
    ]
